In [30]:
#!/usr/bin/env python
# coding: utf-8
import transforms3d as tfs
import numpy as np
import math

def get_matrix_eular_radu(x,y,z,rx,ry,rz,rs="sxyz"):
    rmat = tfs.euler.euler2mat(math.radians(rx),math.radians(ry),math.radians(rz),rs)
    rmat = tfs.affines.compose(np.squeeze(np.asarray((x,y,z))), rmat, [1, 1, 1])
    return rmat


"""
   /* base@grapper  */
    Matrix4d Tbg = TransForms::ComposeEuler(-0.544, -0.203,-0.037, 180, 0.00000, 140);
    /* grapper@camera */
    Matrix4d Tgc  = TransForms::ComposeEuler(0.056,-0.056,-0.106,0,-0,45);
    /*  camera@maker*/
    Matrix4d Tcw  = TransForms::ComposeEuler(0.056,-0.056,-0.106,0,-0,45);
    Matrix4d Tbw  = TransForms::ComposeEuler(-0.663,-0.193,-0.231,-180,0,140);
# Tcg = np.dot(np.linalg.pinv(MA),MB).reshape(3,)
# print(tfs.affines.compose(Tcg,np.squeeze(Rcg),[1,1,1]))
"""
Tbg = get_matrix_eular_radu(-0.544, -0.203,-0.037, 180, 0.00000, 140)
Tgc = get_matrix_eular_radu(0.056,-0.056,-0.106,0,0,45)
Tcw = get_matrix_eular_radu(0.020,-0.040,0.300,0,0,-45)
Tbc = np.dot(Tbg,Tgc)
Tbw = np.dot(Tbc,Tcw)
print(Tbg)
print(Tgc)
print(Tcw)
print(Tbc)
print(Tbw)


[[-7.66044443e-01  6.42787610e-01  7.87187789e-17 -5.44000000e-01]
 [ 6.42787610e-01  7.66044443e-01  9.38133875e-17 -2.03000000e-01]
 [ 0.00000000e+00  1.22464680e-16 -1.00000000e+00 -3.70000000e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 0.70710678 -0.70710678  0.          0.056     ]
 [ 0.70710678  0.70710678  0.         -0.056     ]
 [ 0.          0.          1.         -0.106     ]
 [ 0.          0.          0.          1.        ]]
[[ 0.70710678  0.70710678  0.          0.02      ]
 [-0.70710678  0.70710678  0.         -0.04      ]
 [ 0.          0.          1.          0.3       ]
 [ 0.          0.          0.          1.        ]]
[[-8.71557427e-02  9.96194698e-01  7.87187789e-17 -6.22894595e-01]
 [ 9.96194698e-01  8.71557427e-02  9.38133875e-17 -2.09902383e-01]
 [ 8.65956056e-17  8.65956056e-17 -1.00000000e+00  6.90000000e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[-7.66044443e-01  6.42787610e-01  7.87187789e-17 -6

In [36]:
import transforms3d as tfs
import numpy as np
import math
def get_matrix_eular_radu(x,y,z,rx,ry,rz,rs="sxyz"):
    rmat = tfs.euler.euler2mat(math.radians(rx),math.radians(ry),math.radians(rz),rs)
    rmat = tfs.affines.compose(np.squeeze(np.asarray((x,y,z))), rmat, [1, 1, 1])
    return rmat
rbl = get_matrix_eular_radu(0.043, -0.163, 0.0571,  76,14,-72.511)
rlp = get_matrix_eular_radu(0.300746, 0.096994,0 ,0 ,0 ,0 )
rbl

array([[ 0.29159589,  0.3012824 , -0.90785503,  0.043     ],
       [-0.92544348, -0.15118202, -0.3474167 , -0.163     ],
       [-0.2419219 ,  0.9414738 ,  0.23473578,  0.0571    ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [27]:
np.dot(rbl,rlp)
tfs.euler.mat2euler(np.dot(rbl,rlp)[0:3,0:3])

array([ 0.58633387,  0.54955485, -0.28393939, -0.52304921])

In [37]:
a = np.asarray([0.300746, 0.096994,0])
tfs.euler.euler2mat(76, 14, -72.511)

array([[-0.13233733, -0.75017583, -0.64786037],
       [ 0.03440783, -0.65669189,  0.75337366],
       [-0.99060736,  0.07740798,  0.11271677]])

In [50]:
rbl = get_matrix_eular_radu(0.043, -0.163, 0.0571,  76,14,-72.511)
el = rbl[0:3,0:3]
el

array([[ 0.29159589,  0.3012824 , -0.90785503],
       [-0.92544348, -0.15118202, -0.3474167 ],
       [-0.2419219 ,  0.9414738 ,  0.23473578]])

In [52]:
np.asarray(tfs.euler.mat2euler(el,"rzyx"))*180/3.1415926

array([-72.51100124,  14.00000024,  76.0000013 ])

In [53]:
np.asarray(tfs.euler.mat2euler(el,"sxyz"))*180/3.1415926

array([ 76.0000013 ,  14.00000024, -72.51100124])