In [6]:
#!/usr/bin/env python
# coding: utf-8
import transforms3d as tfs
import numpy as np
import math

def get_matrix_eular_radu(x,y,z,rx,ry,rz):
    rmat = tfs.euler.euler2mat(math.radians(rx),math.radians(ry),math.radians(rz))
    rmat = tfs.affines.compose(np.squeeze(np.asarray((x,y,z))), rmat, [1, 1, 1])
    return rmatzsa


"""
   /* base@grapper  */
    Matrix4d Tbg = TransForms::ComposeEuler(-0.544, -0.203,-0.037, 180, 0.00000, 140);
    /* grapper@camera */
    Matrix4d Tgc  = TransForms::ComposeEuler(0.056,-0.056,-0.106,0,-0,45);
    /*  camera@maker*/
    Matrix4d Tcw  = TransForms::ComposeEuler(0.056,-0.056,-0.106,0,-0,45);
    Matrix4d Tbw  = TransForms::ComposeEuler(-0.663,-0.193,-0.231,-180,0,140);
# Tcg = np.dot(np.linalg.pinv(MA),MB).reshape(3,)
# print(tfs.affines.compose(Tcg,np.squeeze(Rcg),[1,1,1]))
"""
Tbg = get_matrix_eular_radu(-0.544, -0.203,-0.037, 180, 0.00000, 140)
Tgc = get_matrix_eular_radu(0.056,-0.056,-0.106,0,0,45)
Tcw = get_matrix_eular_radu(0.020,-0.040,0.300,0,0,-45)
Tbc = np.dot(Tbg,Tgc)
Tbw = np.dot(Tbc,Tcw)
print(Tbg)
print(Tgc)
print(Tcw)
print(Tbc)
print(Tbw)


[[-7.66044443e-01  6.42787610e-01  7.87187789e-17 -5.44000000e-01]
 [ 6.42787610e-01  7.66044443e-01  9.38133875e-17 -2.03000000e-01]
 [ 0.00000000e+00  1.22464680e-16 -1.00000000e+00 -3.70000000e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 0.70710678 -0.70710678  0.          0.056     ]
 [ 0.70710678  0.70710678  0.         -0.056     ]
 [ 0.          0.          1.         -0.106     ]
 [ 0.          0.          0.          1.        ]]
[[ 0.70710678  0.70710678  0.          0.02      ]
 [-0.70710678  0.70710678  0.         -0.04      ]
 [ 0.          0.          1.          0.3       ]
 [ 0.          0.          0.          1.        ]]
[[-8.71557427e-02  9.96194698e-01  7.87187789e-17 -6.22894595e-01]
 [ 9.96194698e-01  8.71557427e-02  9.38133875e-17 -2.09902383e-01]
 [ 8.65956056e-17  8.65956056e-17 -1.00000000e+00  6.90000000e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[-7.66044443e-01  6.42787610e-01  7.87187789e-17 -6

In [4]:
!pip install numpy

     |████████████████████████████████| 15.4 MB 1.1 MB/s eta 0:00:01    |███▏                            | 1.5 MB 1.1 MB/s eta 0:00:13     |██████▋                         | 3.2 MB 1.1 MB/s eta 0:00:12     |█████████▊                      | 4.7 MB 838 kB/s eta 0:00:13


In [11]:
import rospy